# Generated by Django 2.0.1 on 2018-03-14 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('name', models.CharField(default='Nume contract', max_length=200)),
                ('contract_id', models.CharField(max_length=200)),
                ('start_date', models.DateField(verbose_name='Data semnaturii')),
                ('Data rezilierii', models.DateField(blank=True, null=True)),
                ('payment', models.FloatField(blank=True, null=True)),
                ('Comentariu', models.TextField(blank=True, null=True)),
                ('pdf_contract', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ContractStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.ContractType'),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.ContractStatus'),
        ),
    ]
