# Generated by Django 2.0.1 on 2018-03-14 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='payment',
            new_name='monthly_payment',
        ),
    ]
