# Generated by Django 2.0.1 on 2018-03-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_auto_20180314_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-status']},
        ),
        migrations.AlterField(
            model_name='contract',
            name='pdf_contract',
            field=models.FileField(blank=True, null=True, upload_to='contract/'),
        ),
    ]
