# Generated by Django 2.0.1 on 2018-03-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20180315_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='Data rezilierii',
        ),
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data rezilierii'),
        ),
    ]
