# Generated by Django 2.0.1 on 2018-03-14 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eventtools.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0001_initial'),
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, eventtools.models.OccurrenceMixin),
        ),
        migrations.CreateModel(
            name='PaymentOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('repeat', eventtools.models.ChoiceTextField(blank=True, choices=[('RRULE:FREQ=DAILY', 'Daily'), ('RRULE:FREQ=WEEKLY', 'Weekly'), ('RRULE:FREQ=MONTHLY', 'Monthly'), ('RRULE:FREQ=YEARLY', 'Yearly')], default='')),
                ('repeat_until', models.DateField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.MyEvent')),
            ],
            options={
                'ordering': ('start', 'end'),
                'abstract': False,
            },
            bases=(models.Model, eventtools.models.OccurrenceMixin),
        ),
        migrations.CreateModel(
            name='RecurrentPayment',
            fields=[
                ('date', models.DateField()),
                ('sum', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comments', models.CharField(max_length=200, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='money.Category')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.Contract')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, eventtools.models.OccurrenceMixin),
        ),
        migrations.CreateModel(
            name='SinglePayment',
            fields=[
                ('date', models.DateField()),
                ('sum', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comments', models.CharField(max_length=200, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nb_option', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='money.Category')),
                ('option_pay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='money.PaymentOption')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='option_pay',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='permanentpaymentmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='permanentpaymentmodel',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='permanentpaymentmodel',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('name', 'id')},
        ),
        migrations.DeleteModel(
            name='PaymentModel',
        ),
        migrations.DeleteModel(
            name='PermanentPaymentModel',
        ),
        migrations.AddField(
            model_name='singlepayment',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='money.Subcategory'),
        ),
        migrations.AddField(
            model_name='singlepayment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurrentpayment',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='money.Subcategory'),
        ),
        migrations.AddField(
            model_name='recurrentpayment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
