# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendingentry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.Category'),
        ),
        migrations.AlterField(
            model_name='spendingentry',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.Subcategory'),
        ),
    ]
