# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
