# Generated by Django 2.0.1 on 2018-03-14 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
        ('money', '0002_auto_20180314_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlepayment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.Contract'),
        ),
    ]
