# Generated by Django 2.0.1 on 2018-03-14 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_singlepayment_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentoccurrence',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.RecurrentPayment'),
        ),
        migrations.DeleteModel(
            name='MyEvent',
        ),
    ]
