# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_auto_20170914_1202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpendingEntry',
            new_name='PaymentModel',
        ),
    ]
