# Generated by Django 2.0.1 on 2018-03-14 20:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0002_auto_20180314_2012'),
        ('money', '0004_auto_20180314_1944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SinglePayment',
            new_name='Payment',
        ),
    ]
