# Generated by Django 2.0.1 on 2018-03-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_auto_20180314_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='nb_option',
            new_name='nb_tickete',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='option_pay',
        ),
        migrations.DeleteModel(
            name='PaymentOption',
        ),
    ]
