# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_auto_20170914_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='option_pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.PaymentOption'),
        ),
    ]
