# Generated by Django 2.0.1 on 2018-03-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_auto_20180314_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='nb_tickete',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
