# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_auto_20170917_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentoption',
            name='nume',
            field=models.CharField(max_length=15),
        ),
    ]
