# Generated by Django 2.0.1 on 2018-03-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0007_auto_20180314_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentoccurrence',
            old_name='event',
            new_name='payment',
        ),
    ]
