# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0008_auto_20170917_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='nb_option',
            field=models.IntegerField(default=0),
        ),
    ]
