# Generated by Django 2.0.1 on 2018-03-18 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0010_auto_20180317_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentoccurrence',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.RecurrentPayment'),
        ),
        migrations.DeleteModel(
            name='MyEvent',
        ),
    ]
