# Generated by Django 2.0.1 on 2018-03-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0011_auto_20180318_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recurrentpayment',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
