# Generated by Django 2.0.1 on 2018-03-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0012_auto_20180318_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='recurrentpayment',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
