# Generated by Django 2.1.7 on 2019-02-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0014_revenue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id', 'name', 'description'), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date'], 'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['id'], 'verbose_name': 'subcategory', 'verbose_name_plural': 'subcategories'},
        ),
    ]
