# Generated by Django 2.1.7 on 2019-02-25 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0016_auto_20190220_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 25, 10, 30, 8, 266618)),
        ),
    ]
