# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
